name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: yuluoqingcheng
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          config_padding: 6%
          optimize: svg
          experimental_features: --optimize-svg

          # 3D 等距贡献日历
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # 编程语言统计
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6

          # 代码行数统计
          plugin_lines: yes

          # Star 趋势图
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
